global:
  scrape_interval: 15s

scrape_configs:
  - job_name: kraken
    static_configs:
      - targets: ['kraken.lan:9100']
      
  - job_name: rodan-metrics
    static_configs:
      - targets: ['localhost:9100']
      
  - job_name: bitcoind-exporter
    static_configs:
      - targets: ['localhost:9332']
      
  - job_name: 'snmp'
    static_configs:
      - targets:
        - upstairsap.lan  # SNMP device.
        - downstairsap.lan # SNMP device.
        - deckap.lan
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.
